development: 
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: JustGtv-development
  password: 4144

test: 
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: JustGtv-test
  password: 4144

production: 
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: JustGtv
  password: 4144
